import { DM_Sans, Lora } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { dark } from "@clerk/themes";
import Header from "@/components/Header";

import { Toaster } from "@/components/ui/sonner";
const lora = Lora({
  subsets: ['latin'],
  weight: ["400", "500"],
  style: ["normal", "italic"],
  variable: "--font-lora"

})
const dmSans = DM_Sans
  ({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-dm-sans",
  });
export const metadata = {
  title: "Prept",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      theme: dark,
    }}>
      <html
        lang="en" suppressHydrationWarning
      >
        <body className={`${lora.variable} ${dmSans.variable} font-sans min-h-screen flex flex-col`}>

          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="flex-1 min-h-0 pt-20">
              {children}
            </main>

            <Toaster richColors />
            {/* <Footer /> */}

          </ThemeProvider>

          <footer className="relative z-10 border-t border-white/7 py-12
       mx-auto px-6 flex items-center justify-center text-stone-400">
            Made with ❤️ by {"vidya"}
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
